/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const MarketUpdate = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'authorId' : IDL.Principal,
  'publishedAt' : IDL.Int,
  'summary' : IDL.Text,
  'category' : IDL.Text,
});
export const UserPrefs = IDL.Record({
  'followedCategories' : IDL.Vec(IDL.Text),
  'userId' : IDL.Principal,
  'lastVisitTime' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createUpdate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [IDL.Nat],
      [],
    ),
  'deleteUpdate' : IDL.Func([IDL.Nat], [], []),
  'editUpdate' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getNewUpdatesCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUpdateById' : IDL.Func([IDL.Nat], [IDL.Opt(MarketUpdate)], ['query']),
  'getUpdates' : IDL.Func([], [IDL.Vec(MarketUpdate)], ['query']),
  'getUpdatesByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MarketUpdate)],
      ['query'],
    ),
  'getUserPrefs' : IDL.Func([], [UserPrefs], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initMarketScoutApp' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordVisit' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveUserPrefs' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const MarketUpdate = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'authorId' : IDL.Principal,
    'publishedAt' : IDL.Int,
    'summary' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserPrefs = IDL.Record({
    'followedCategories' : IDL.Vec(IDL.Text),
    'userId' : IDL.Principal,
    'lastVisitTime' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createUpdate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [IDL.Nat],
        [],
      ),
    'deleteUpdate' : IDL.Func([IDL.Nat], [], []),
    'editUpdate' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getNewUpdatesCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUpdateById' : IDL.Func([IDL.Nat], [IDL.Opt(MarketUpdate)], ['query']),
    'getUpdates' : IDL.Func([], [IDL.Vec(MarketUpdate)], ['query']),
    'getUpdatesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MarketUpdate)],
        ['query'],
      ),
    'getUserPrefs' : IDL.Func([], [UserPrefs], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initMarketScoutApp' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordVisit' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveUserPrefs' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };