/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MarketUpdate {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'authorId' : Principal,
  'publishedAt' : bigint,
  'summary' : string,
  'category' : string,
}
export interface UserPrefs {
  'followedCategories' : Array<string>,
  'userId' : Principal,
  'lastVisitTime' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createUpdate' : ActorMethod<
    [string, string, string, string, bigint],
    bigint
  >,
  'deleteUpdate' : ActorMethod<[bigint], undefined>,
  'editUpdate' : ActorMethod<
    [bigint, string, string, string, string, bigint],
    undefined
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getNewUpdatesCount' : ActorMethod<[], bigint>,
  'getUpdateById' : ActorMethod<[bigint], [] | [MarketUpdate]>,
  'getUpdates' : ActorMethod<[], Array<MarketUpdate>>,
  'getUpdatesByCategory' : ActorMethod<[string], Array<MarketUpdate>>,
  'getUserPrefs' : ActorMethod<[], UserPrefs>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initMarketScoutApp' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordVisit' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveUserPrefs' : ActorMethod<[Array<string>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];